ansible_become_pass: ENC[AES256_GCM,data:UbhFSSyf9cE=,iv:BuD3FCOu6paXDGQdxov+4ZKmv+CqMDQbY8ogpmHb5Qk=,tag:7zznWh4EqBSBp283yc714Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNGNZaFBqaC9HN0FNRmx3
            OTRWQ1k2a1MzUDBPVWVzY3BUUWFJR0FvbkNZCkl2dk9UWWQwSVp5OWlxSU1sSWlE
            amFwYVZHOGRqdFd1WnFiTmNyb1hyQzQKLS0tIHRtOEJrTE10dHhWUTlmbks3T0tr
            aWNPaHJKUCtnSFhTVWY3NS8xNTNQVkEKNlEq1L8Ix5ijNt8ICLFCxbc0qt7b+XhT
            C0nsaKfDxKIR+n2NUJ3trXj4+m1GOGT/AmAzxQtz9QZHhwI0X8xPCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T19:48:18Z"
    mac: ENC[AES256_GCM,data:K2FU25OCP5b6PiqRR0WjV6nSVfupUuTWaMCSesqNbHXB8yQCJvPG4C6cw2HMJdF2wPgyl2XpbSMeGS4k/Fd1vb+3plj6ru6/DGbPdWM85iH9bEl3K04FimwSgQzSEZWyogYgJ5JhcDgPnLB3C1V86mXOfk3XJzLF5hFChV3VPXY=,iv:R53GVfzB699jWrvpBsNnsGTSbZV73/nh47eFwhmwcrA=,tag:hKFCODBA5BVbqA9dbt9bwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
