ansible_become_pass: ENC[AES256_GCM,data:4PaOpuxVZd8=,iv:hPvZ4zxVYQCW2nR+gHWrt5F8G4VVPRirZf1RxHV/lrc=,tag:kigFeVXX+D3BrrGwfN9k2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVE9OODZOOVYzN2Qrd2Vs
            NG1mbEI3cEJobnNhSFJ6UmZNeUJGQ3MrZGxrCmFHODc3UEt5Ui85bXYzenBkWEZE
            aGprOHBGYmQ2akFyNXpiaEJEQjVLL0kKLS0tIERWdjBoaCtaNXdTbWdIZUJCZ1VJ
            ZndXS1RaaGFCenRGc0lIUENvZTRIZ00K/Mn404eMKGqpjq5E2HHoDV4Geef040wZ
            zusIeRoOKCsOkPRwBa71V7xlHCA+6tHNgajqa868XiwGSC0uh2HXbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T21:23:36Z"
    mac: ENC[AES256_GCM,data:ooPisg/EcP+lAekjrB8tZPmSEssc4nIRrm8TURt9/24yYW07HBEe7M73AZr2gkiuMcyGOIcSin2QKMLObT0V2NQDl9Dv6lsyWtPWJrvd8591eckvZdTFvQvo+ie8/e1Pd4q7XRJH84+5bDyHdzKjo4ja2RKq1J2EUpURLi0aluQ=,iv:IQmbOKNJL9cbUMXa4dht9Nh9i2gaJ93jWiCxgiD5DGU=,tag:9kvMohUUHMKQYRF/fwiY6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
