apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: br-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: br-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: br-cf-token-secret
              key: api-token
        selector:
          dnsZones:
            - "${BR_SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: br-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: br-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: br-cf-token-secret
              key: api-token
        selector:
          dnsZones:
            - "${BR_SECRET_DOMAIN}"
