---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data-test
  namespace: wordpress
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
#  storageClassName: ceph-filesystem
