---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-config-test
  namespace: wordpress
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metedata:
  name: wordpress-database-test
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
