---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data-test
  namespace: wordpress
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 26Gi
  storageClassName: ceph-filesystem
