---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-data-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
#  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
  volumeName: "wp-data-pv"
