---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-config-test
  namespace: wordpress
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 25Gi
  storageClassName: ceph-filesystem
