apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:5XbLMwZKX6JpNtITtP8zPQQu+BtRcE3M52Zom/0EaPDfBEYDmYQ5Qo/dmRgh2zssXfqPk5hjdEiuEYxN,iv:HPoAe6euErByotXJ4eUbfgI2y/dFdRYOn3DftuMQ6n8=,tag:6k1zrc6JE+cAS5AjfnhiMg==,type:str]
    username: ENC[AES256_GCM,data:BUAvZAI=,iv:Qw3HFUqSpgMbq36+uMJq5BXIFGYxH+3upCfFxQvEPl4=,tag:9PjZrv6VB6JWJJWTHBO18A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVN3TUdtNXRwTFVDRjcy
            N3lwY1phci9NYjlQWUpRdS9yMVhEd3M5NXlZCmo1V1Nla2I0OHhPbXFpT3dLVlRD
            aUUxUllLRy9GMEhZaU1LNXA4aHZueDQKLS0tIFFCbEVDUk5yb2kveDREQkp6Z1Fs
            S2l0SUt0TVBnd1lHaDQyZlFtei83dVUK2iETZeR3B8yixfN3k4xYh8pUAhJBtEY5
            ML/rhwoXppcXjzlE53BnIicO4G3Msisamc2k5ckR3e8lfwQKUGoz7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T19:48:54Z"
    mac: ENC[AES256_GCM,data:u7gZrMQ/nqx2CXsId79FoufcqA9YzSdAbSrOrj1CgxA3VSIVIsdD6v3V86qR7mY9zzn2bnNFh7QWSycqqOoAEy1OO+y6/HIY0QqQly+VcLi9jBTeS116Ri+8m08tf5QuiTDhizer263vssKT5eUAMLNkQ0cIJ9xg9UW/Nqnr8Io=,iv:NeIneOZFjQ6b+AJo7V/hJSUGIFW+Jf+OQHcYxvA8FFw=,tag:j9AnDzF7KOtDFFlx6H6M8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
