---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${BR_SECRET_DOMAIN/./-}-production"
#  namespace: wordpress
spec:
  secretName: "${BR_SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: br-production
    kind: ClusterIssuer
  commonName: "${BR_SECRET_DOMAIN}"
  dnsNames:
    - "${BR_SECRET_DOMAIN}"
#    - "*.${BR_SECRET_DOMAIN}"
