---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${LINS_SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${LINS_SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: lbproduction
    kind: ClusterIssuer
  commonName: "${LINS_SECRET_DOMAIN}"
  dnsNames:
    - "${LINS_SECRET_DOMAIN}"
#    - "*.${LINS_SECRET_DOMAIN}"
