---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${LINS_SECRET_DOMAIN/./-}-production"
#  namespace: wordpress
spec:
  secretName: "${LINS_SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: lb-production
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "app=kubed" # Sync certificate to matching namespace
  commonName: "${LINS_SECRET_DOMAIN}"
  dnsNames:
    - "${LINS_SECRET_DOMAIN}"
#    - "*.${LINS_SECRET_DOMAIN}"
