apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AqEQHi95AGH7HJV7mnWMucIqhPNcQrc=,iv:asbKa7DmZJux3RNUZS8vK8kjQqc3qorqpLxcloZO8rg=,tag:nEIqyEXmLfCVodp22oPS1A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/EJ5bHuC2R6qkns23aV8bY0KWZSp2aAotGOyfZxUZZ1PxNtC,iv:X/vhAuP9/AaNxgARBHNuHGLWMmST7FZRJBpQ/5mjHyQ=,tag:54PmrH2vahK0mu30OjE+4w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:hH6cOlGLJlvbjK7BR77y,iv:LKkP1B14x3+M7ZREQpEsrx+iAhnaNmqUmM8uVjxTW+4=,tag:IuV3ov0iC0yON0qB9dnXhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVG9HalN5V1BxK3FGTlFM
            aVJpY29sd2RwU0huUkl0WTJnOTdFYlcyVnlvCkRxbnl5eGV2VEFaR3FGVEtvWUYw
            aHdLQUlzdTJMTldUQ1FMc0tJUEVzdGcKLS0tIHA3T3ZFNFJxckdkMDV6b3VOaTR6
            QXE4NEUyWHNCMHU2OFBaYVc2Z25WZmsK/9kuLUZ2ldYbWt3vrOxAOsh6+9uD2r8O
            xnuNNXLmZqpid+t5/8UYyrBZp0RzZK4MPcsPQzoce0f7WmuSvawXyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T21:24:04Z"
    mac: ENC[AES256_GCM,data:YNua3HoNjvjwQxxTY5h7mRd/zeQLgJp3JDt3W3SpIxX5hNAHPHLXKSpQp2d/7pakN0MwCEzyeUFyTbAWgQ0pn3oNewP/zhYpJLPFy8zzYJnUHPlFQ6c6vlosxuDsxUqy4S1YkGNAXAdXIT/pP9+kLFUzUj5TaOozL3IdJLxqhNA=,iv:58I8ExEij9PcuS0tP6Ugwzw2TjuOHGCjHIqNWQsDU5g=,tag:EiRJ9uGnYD/UPMZ28Gj8kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
