apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:RPCJAV3+rQzz3QgF,iv:FfMce0KUntt6fek5T9I/Dls7cTFrWSIQocRGAc17aSg=,tag:73vG/RvRZxgaCxNYP5whtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeUh2NkQxd3c4UElnL1ZS
            WU4zMEk1T1A1MmUyTXh3UE5JOEJ5ZEg0TzNjCkkyakhvcUhKdVM0V1ZiZGtzMXlN
            Um9MdDZhSmQvZkZKZUUwUGZJWmQwbVUKLS0tIDdrSTRyc01ydGxsc1N1Vy96YWRS
            c09zenJnWTYwZWVEL1N5TGQ4UVhiSU0KCvTyN3ldeIZi7qzd+dLP0LCOpdhWITR4
            4fiSnVVgSmwLIl+uViYtth+cNWCfwIpayz1gI+NH+rwiP/o3DokeHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T19:48:47Z"
    mac: ENC[AES256_GCM,data:PaniAXPI1Px4hQoIDQqrbxRxSVXdHpxVWq3eJPHBsyOCkzuXjkIKPFmKf408Av0iYAMjoIFhpT5ApQu1GaURIWGGzEyl4zg+gxCgaqsWAPCwT3POP+awFmNMl54FL3IG1HgH3ACsNDdT0Rn+BoM/6NX5wv+or4XZAURIc3wuW5Q=,iv:v7MPfPkU/6hnqOCbkNBzLefj/8fyzHEkSnNx7R+tjHE=,tag:cc38zu9xwBjwLbmxrC+llQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
