---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-config
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-filesystem
