apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GJNNAdFGrGu3YyatblSg/0j72OnDbSrg0nhEzK2YPh19hVze,iv:epdxMuACQ+Nuz/KJoZs9srfeh1e9QCkyz8FcQUd8qew=,tag:asDZgAACc/2gTkTFstA5Bw==,type:str]
    credentials.json: ENC[AES256_GCM,data:rSANFj7/1+Z/o3x772fqvHhBd315EXmI2vb9qIUIJ2kEp2TRlov83AThzk1r8CHf4WHkSZjySwB0tYZBIFInQ30WtW0Au1avnQmKDP+Xmnm8OSsY3k9LlPPtp9iNSr3xvVG5RalC0VvfWMzY/QGzqfybjqRxZ/BipKqpRIwHiBlQGrfIkHYqwiHUsqwPb3YkFDM5HjlN+14FqNbgbnGJ2F/jXUfu3boJ80GIH7qY9A==,iv:bctByRhVS1SzSWXtlcSfurufSqGX5hVjLku46jsB0SE=,tag:4tfnVuNAxAw4PdCKjTHrPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqf2aadn2pt923ahgl54q8sklnf5up9rxphzzufkuwlv4ut6asvqpyck32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbFpyTDFKdHBVQ3dsaFZu
            WDVwSlRxWFBhQ2ZsZ0poUk9RT1RnclVLK2h3ClZhRTlFUktTcGhackVKcGJxRXRk
            OWpBaUV3YldPWUxXRGYxb1BzRUlwNk0KLS0tIHorTm00dFVXdDZVcS9YUEd4M2hp
            VURONXZtdkprM2w5Z1hRVnhKbldnTTQKKhCT2W2b19StJbhyhRj+V3T754FoZzky
            686yYU+dWENNSBTRE2/TKER54dIkHdXIxnL8zJcHsB+4k34J3HyzeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T19:48:47Z"
    mac: ENC[AES256_GCM,data:hTYOU+Lb1T0ozcPwtPZqAyMY9aihwDzLU9s2H4tWarqJcQifpJNJKtPsZ0o1sZ3r8vuN9ucRAWIOUux6fgwJyr2H1BBVoAgeMb5evFyNDDiTz2HbMZ23XyzxN43zy0nuGd/vlPPgoIFjO0k3yfvTBt0UyfuxF2hR6Od/Rg9tiJ4=,iv:aXHSy4iWxbPKppi+e6w3+DkoQ39tTYmPyyD23Sp/1uY=,tag:p1/fHfId/bJLEii1QxgEZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
