---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
